throw new Error();
console.log('Hello from after the error!');